int search_loop(FILTERED_SPECTRUM_CHARGE_ITERATOR_T* spectrum_iterator,
		BOOLEAN_T combine_target_decoy,
		int num_peptide_mods,
		PEPTIDE_MOD_T** peptide_mods,
		DATABASE_T* database,
		INDEX_T* index,
		int sample_per_pep_mod,
		BOOLEAN_T compute_pvalues,
		void* output_files_param,
		int num_decoys);
